name: pullrequest
on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo "The event type is ${{ github.event.action }}"
